

   
DEFAULT_KERNEL_TYPE = "dot"
DEFAULT_SIMFUNC = "abs_diff"
DEFAULT_NOSPHERE = False
DEFAULT_VARIABLE_NAME = "data"
DEFAULT_INPUT_PATH = "./"
DEFAULT_OVERWRITE = False
DEFAULT_NOVERIFY = False
DEFAULT_VERBOSE = False
DEFAULT_USE_CACHE = False
